### ISSUE TITLE
GA Tracking for Staking 

### ISSUE THREAD

**Issue by josietyleung** [EmerisHQ/demeris#1362]
1. How many of our users are using Emeris for the Staking feature/ which feature is the most popular one? 
Custom events for “action start” and “action success” for 
- [x] Claim Rewards 
- [x] Stake
- [x] Unstake
- [x] Restake

2. Popularity of entry points. Both click-through rate & conversion rate (click + actually made a staking tx). Custom events for: 
- [x] Banner on portfolio page 
- [x] Banner on asset page 
- [x] + stake button on asset page 
- [x] 3 dots’ > stake button on asset page 

3. Whether the Unstaking view is useful. Custom event for: 
- [x] Clicking on the Unstaking view for users with unstaking assets 

4. Whether users stake to multiple validators. Custom event for: 
- [x] Clicking on the + Add a validator button when staking 

Staking Section in the [Gdoc](https://docs.google.com/document/d/1KzDBborcdbplI11H_vIUg_8DM0WAqeXd0cAK0KMAzAo/edit) for more details. 
Slack thread [here](https://allinbits.slack.com/archives/C0324SMSKC2/p1647495515832519). 

Thanks!
